<?php $this->headScript()->appendFile('/js/menu.js'); ?>
<div class="dcontent">
    <div style="margin-left: 10px;">
        <?php foreach($this->dates as $date):?>
            <a href="/menu/<?=$date['timestamp']?>" class="<?=$date['class']?>"><?=$date['date']?></a>
        <?php endforeach;?>
    </div>

    <div class="top">
        <input type="button" class="button3 create_menu_catalog" id="<?=$this->dateNow->getTimestamp()?>" value="Сформировать на основе каталога блюд" />
        <a href="#null" class="button1 showDeleted fl_r">Показать удаленные</a>
    </div>
    <?php if(count($this->menus) != 0):?>
        <ul>
        <?php
            $group = "";
            foreach($this->menus as $menu)
            {
                $dg = $menu->getDish()->getGroup()->getName();
                if ($group != $dg)
                {
                    echo "<li class='li_group p10'>$dg";
                }

                if($menu->isDeleted())
                {
                    $button = "<button class='button2 fl_r include' id='{$menu->getId()}'>Включить в меню</button>";
                    $class = "li_dish_deleted";
                } else {
                    $class = "";
                    $button = "<button class='button2 fl_r exclude' id='{$menu->getId()}'>Исключить из меню</button>";
                }

                echo "
                    <li class='li_dish $class'>
                        <table>
                            <tr>
                                <td style='width:530px; padding-left:10px;'>
                                    {$menu->getDish()->getName()}
                                </td>
                                <td>
                                    $button
                                </td>
                            </tr>
                        </table>
                    </li>";
                if ($group != $dg)
                {
                    $group = $dg;
                    echo "</li>";
                }
            }
        ?>
        </ul>
    <?php else:?>
        <div>На этот день меню не сформировано</div>
    <?php endif;?>
</div>