<?php $this->headScript()->appendFile('/js/knockout.js'); ?>
<?php $this->headScript()->appendFile('/js/new_menu.js'); ?>
<div class="dcontent">

    <div style="margin-left: 10px;" id="<?=$this->dateNow->getTimestamp()?>" class="curDate">
        <?php foreach($this->dates as $date):?>
            <a href="/newMenu/<?=$date['timestamp']?>" class="<?=$date['class']?>"><?=$date['date']?></a>
        <?php endforeach;?>
    </div>

    <div class="top">
        <input type="text" class="txt_find" placeholder="Введите название блюда" value="" />
        <div class="fl_r" style="padding:4px 2px 2px 0;"><button class="button3 btt_mini2">добавить все</button></div>
        <ul class="list_menu">
            <li>Свинина по армянски <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по русски <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по грузински <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по туркменски <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по русски <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по грузински <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по туркменски <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по русски <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по грузински <button class="button3 btt_mini2 fl_r">добавить</button></li>
            <li>Свинина по туркменски <button class="button3 btt_mini2 fl_r">добавить</button></li>
        </ul>
    </div>

    <div class="week_menu">
        <table class="table_menu">
            <thead>
                <tr>
                    <td colspan="10">Меню на неделю</td>
                </tr>
                <tr>
                    <td width=400>Блюдо</td>
                    <td width=60>Цена</td>
                    <td width=20>Пн.</td>
                    <td width=20>Вт.</td>
                    <td width=20>Ср.</td>
                    <td width=20>Чт.</td>
                    <td width=20>Пт.</td>
                    <td width=20>Сб.</td>
                    <td width=20>Вс.</td>
                </tr>
            </thead>
            <tbody data-bind="foreach: MenuModel.currentMenu">
                <tr>
                    <td colspan="10" data-bind="text: key" style="font-weight: bold"></td>
                </tr>
                <!-- ko foreach: val -->
                <tr>
                    <td data-bind="text: key"></td>
                    <td data-bind="text: cost"></td>
                    <td><input type="checkbox" id="1"/></td>
                    <td><input type="checkbox" id="1"/></td>
                    <td><input type="checkbox" id="1"/></td>
                    <td><input type="checkbox" id="1"/></td>
                    <td><input type="checkbox" id="1"/></td>
                    <td><input type="checkbox" id="1"/></td>
                    <td><input type="checkbox" id="1"/></td>
                    <td><button id="1" class="button2 btt_mini">удалить</button></td>
                </tr>
                <!-- /ko -->
            </tbody>
        </table>
    </div>
</div>