<?php $this->headScript()->appendFile('/js/orders.js'); ?>
<div class="dcontent">
    <div style="margin-left: 10px;">
        <?php foreach($this->dates as $date):?>
            <a href="/allorder/user/<?=$date['timestamp']?>" class="<?=$date['class']?>"><?=$date['date']?></a>
        <?php endforeach;?>
    </div>
    <div class="top">
        <div class="label fl_l" id="<?=$this->dateNow->getTimestamp()?>">
            Всего заказов - <?=count($this->orders)?>
        </div>
        <div class="label fl_l" style="padding-left: 10px;" id="<?=$this->dateNow->getTimestamp()?>">
            на сумму - <?=$this->total?>
        </div>
        <a href="/allorder/dish/<?=$this->dateNow->getTimestamp()?>" class="button1 fl_r">По блюдам</a>
    </div>
    <?php if(count($this->orders) != 0):?>
        <ul>
            <li class='<?=$this->class?> p10'>
                <table>
                    <tr>
                        <td style='width:530px; padding-left:10px;'>
                            Сотрудник
                        </td>
                        <td width=30>
                            Стоимость
                        </td>
                    </tr>
                </table>
            </li>
            <?php
            $group = "";
            foreach($this->orders as $order)
            {
                echo "
                    <li class='li_dish p10'>
                        <table>
                            <tr>
                                <td style='width:530px; padding-left:10px; font-size: 14px'>
                                    {$order->getUser()->getUsername()}
                                </td>
                                <td width=30>
                                    {$order->getTotal()}
                                </td>
                            </tr>
                        </table>
                    </li>";
            }
            ?>
        </ul>
    <?php else:?>
        <div>На этот день заказов пока нет</div>
    <?php endif;?>
</div>