<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Location;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Location extends \Application\Entity\Location\Location implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function checkAccess(\Application\Entity\User\ZfcUser $user)
    {
        $this->__load();
        return parent::checkAccess($user);
    }

    public function getAvailableLocation()
    {
        $this->__load();
        return parent::getAvailableLocation();
    }

    public function fromArray(array $data = array (
))
    {
        $this->__load();
        return parent::fromArray($data);
    }

    public function toJson()
    {
        $this->__load();
        return parent::toJson();
    }

    public function fromJson($data = '')
    {
        $this->__load();
        return parent::fromJson($data);
    }

    public function getProtectedProperties()
    {
        $this->__load();
        return parent::getProtectedProperties();
    }

    public function isProtectedProperty($property)
    {
        $this->__load();
        return parent::isProtectedProperty($property);
    }

    public function __call($method = NULL, $arguments = array (
))
    {
        $this->__load();
        return parent::__call($method, $arguments);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'description', 'available', 'access');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}