<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\User;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ZfcUser extends \Application\Entity\User\ZfcUser implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getDisplayName()
    {
        $this->__load();
        return parent::getDisplayName();
    }

    public function setDisplayName($displayName)
    {
        $this->__load();
        return parent::setDisplayName($displayName);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function addContact(\Application\Entity\User\UserContact $contact)
    {
        $this->__load();
        return parent::addContact($contact);
    }

    public function addWall(\Application\Entity\Wall\UserWall $wall)
    {
        $this->__load();
        return parent::addWall($wall);
    }

    public function getFullname()
    {
        $this->__load();
        return parent::getFullname();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getWall($offset = NULL, $length = NULL)
    {
        $this->__load();
        return parent::getWall($offset, $length);
    }

    public function fromArray(array $data = array (
))
    {
        $this->__load();
        return parent::fromArray($data);
    }

    public function toJson()
    {
        $this->__load();
        return parent::toJson();
    }

    public function fromJson($data = '')
    {
        $this->__load();
        return parent::fromJson($data);
    }

    public function getProtectedProperties()
    {
        $this->__load();
        return parent::getProtectedProperties();
    }

    public function isProtectedProperty($property)
    {
        $this->__load();
        return parent::isProtectedProperty($property);
    }

    public function __call($method = NULL, $arguments = array (
))
    {
        $this->__load();
        return parent::__call($method, $arguments);
    }

    public function __get($name)
    {
        $this->__load();
        return parent::__get($name);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'email', 'displayName', 'password', 'state', 'created', 'firstname', 'lastname', 'middlename', 'lastactive', 'sex', 'birthday', 'avatar', 'avatarmini', 'status', 'city', 'post', 'group', 'contacts', 'wall', 'company');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}