<?php $this->headScript()->appendFile('/js/catalog.js'); ?>
<div class="dcontent">
    <div></div>
    <div class="top">
        <?=$this->name?>
        <a href="#null" class="button1 showDeleted fl_r">Показать удаленные</a>
    </div>
    <a href="#null" id="<?=$this->id;?>" class="button3 btt_add_dish">Добавить</a>
    <ul>
        <?php foreach($this->dishes as $dish):?>
            <?php if($dish->isDeleted()):?>
                <li class="li_dish li_dish_deleted">
                    <table>
                        <tr>
                            <td><input class="geoTXT txt_name" type="text" id="<?=$dish->getId();?>" value="<?=$dish->getName()?>" /></td>
                            <td><input class="geoTXT txt_cost" type="text" id="<?=$dish->getId();?>" value="<?=$dish->getCost()?>" /></td>
                            <td>
                                <a href='#null' id='<?=$dish->getId();?>' class='button3 btt_ret'>Вернуть</a>
                            </td>
                        </tr>
                    </table>
                </li>
            <?php else:?>
                <li class="li_dish">
                    <table>
                        <tr>
                            <td><input class="geoTXT txt_name" type="text" id="<?=$dish->getId();?>" value="<?=$dish->getName()?>" /></td>
                            <td><input class="geoTXT txt_cost" type="text" id="<?=$dish->getId();?>" value="<?=$dish->getCost()?>" /></td>
                            <td>
                                <a href='#null' class='button2 btt_del'>Удалить</a>
                                <a href='#null' id='<?=$dish->getId();?>' style='display: none;' class='button4 btt_confirm_name'>Да!</a>
                            </td>
                        </tr>
                    </table>
                </li>
            <?php endif;?>
        <?php endforeach;?>
    </ul>
</div>
