<?php $this->headScript()->appendFile('/js/catalog.js'); ?>
<div class="dcontent">
    <h3>Каталог блюд (данные сохраняются как только поле ввода потеряло фокус)</h3>
    <ul>
        <?php foreach($this->groups as $group):?>
            <li>
                <?php $dishs = $group->getDish();?>
                <?php if(count($dishs) != 0):?>
                    <ul>
                        <li class="li_group">
                            <table>
                                <tr>
                                    <td><input class="geoTXT txt_group" type="text" id="<?=$group->getId();?>" value="<?=$group->getName();?>" /></td>
                                    <td><a href="#" id="<?=$group->getId();?>" class="button3">Добавить</a></td>
                                    <td>
                                        <a href="#" class="button2 btt_del">Удалить</a>
                                        <a href="#" id="<?=$group->getId();?>" style="display: none;" class="button4 btt_confirm_group">Да!</a>
                                    </td>
                                </tr>
                            </table>
                        </li>
                        <?php foreach($dishs as $dish):?>
                            <li class="li_dish">
                                <table>
                                    <tr>
                                        <td><input class="geoTXT txt_name" type="text" id="<?=$dish->getId();?>" value="<?=$dish->getName()?>" /></td>
                                        <td><input class="geoTXT txt_cost" type="text" id="<?=$dish->getId();?>" value="<?=$dish->getCost()?>" /></td>
                                        <td>
                                            <a href="#" class="button2 btt_del">Удалить</a>
                                            <a href="#" id="<?=$dish->getId();?>" style="display: none;" class="button4 btt_confirm_name">Да!</a>
                                        </td>
                                    </tr>
                                </table>
                            </li>
                        <?php endforeach;?>
                    </ul>
                <?php endif;?>
            </li>
        <?php endforeach;?>
    </ul>
</div>