<?php $this->headScript()->appendFile('/js/catalog.js'); ?>
<div class="dcontent">
    <div></div>
    <div class="top">
        <div class="capt">Каталог блюд</div>
    </div>
    <ul>
        <li class="li_add_group">
            <input type="text" class="geoTXT txt_group_add" />
            <a href="#null" style="padding:3px 19px 4px" class="button3 btt_add_group">Добавить раздел</a>
        </li>
    </ul>
    <ul>
        <?php foreach($this->groups as $group):?>
            <li>
                <ul>
                    <li class="li_dish">
                        <table>
                            <tr>
                                <td><input class="geoTXT txt_group" type="text" id="<?=$group->getId();?>" value="<?=$group->getName();?>" /></td>
                                <td><a href="/catalog/group/<?=$group->getId();?>" class="button1">Перейти</a></td>
                                <td>
                                    <a href="#null" class="button2 btt_del">Удалить</a>
                                    <a href="#null" id="<?=$group->getId();?>" style="display: none;" class="button4 btt_confirm_group">Да!</a>
                                </td>
                            </tr>
                        </table>
                    </li>
                </ul>
            </li>
        <?php endforeach;?>
    </ul>
</div>
