<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
//                        ->prependStylesheet($this->basePath() . '/js/geoupload/fancyBox/source/jquery.fancybox.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      	->prependFile($this->basePath() . '/js/jquery.min.js')
//                                        ->appendFile($this->basePath() . '/js/geoupload/fancyBox/source/jquery.fancybox.pack.js')
                ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a style="text-decoration: none;" href="<?=$this->url('order')?>">
                    	<div class="logo">Обеды</div>
                    </a>
                    <ul class="nav" style="float:right;">
                        <li><a href="/order">Сделать заказ</a></li>
                        <li><a href="/user">Мои данные</a></li>
                        <li><a href="/user/logout">Выйти из системы</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container content">
        	<div class='left_col'>
                <a href="/catalog" id="l_catalog" class="button1" style="width:180px;font-size:14px;"><li>Каталог блюд</li></a><br>
                <a href="/newMenu" id="l_menu_new" class="button1" style="width:180px;font-size:14px;"><li>Создать меню (новое)</li></a><br>
                <a href="/allorder" id="l_orders" class="button1" style="width:180px;font-size:14px;"><li>Все заказы</li></a><br>
                <a href="/eating" id="l_eating" class="button1" style="width:180px;font-size:14px;"><li>Кто что ест</li></a><br>
            </div>
        	<div class='center_col'>
	            <?php echo $this->content; ?>
        	</div> <!-- /center_col -->
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
