<?php $this->headScript()->appendFile('/js/user.js'); ?>
<?php $this->headScript()->appendFile('/js/colorpicker.min.js'); ?>
<style type="text/css">
    #picker, #picker-color { width: 150px; height: 150px; cursor: crosshair }
    #slide, #slide-color { width: 30px; height: 150px; cursor: crosshair; }
    #example { width:300px; text-align: center; outline: none; padding:5px 20px; font-size: 18px; font-weight: bold; border-radius: 12px; }
    #slide-color{ margin-left:20px; }
</style>

<div style="padding:20px;min-height: 300px;">

    <table style="margin: 0 auto;">
        <tr>
            <td colspan="4" align=center>
                <input type="text" id="example" value="<?=$this->zfcUserDisplayName()?>"
                       style="
                           background-color: <?=$this->zfcUserIdentity()->getBackcolor()?>;
                           color: <?=$this->zfcUserIdentity()->getColor()?>" />
            </td>
        </tr>
        <tr>
            <td colspan="2" align=center>Цвет фона</td>
            <td colspan="2" align=center style="padding-left:20px;">Цвет текста</td>
        </tr>
        <tr>
            <td>
                <div id="slide"></div>
            </td>
            <td>
                <div id="picker"></div>
            </td>
            <td>
                <div id="slide-color"></div>
            </td>
            <td>
                <div id="picker-color"></div>
            </td>
        </tr>
    </table>
    <script type="text/javascript">
    </script>
</div>