<?php $this->headScript()->appendFile('/js/order.js'); ?>
<div class="dcontent">
    <div style="margin-left: 10px;">
        <?php foreach($this->dates as $date):?>
            <a href="/order/<?=$date['timestamp']?>" class="<?=$date['class']?>"><?=$date['date']?></a>
        <?php endforeach;?>
    </div>
    <?php
        $total = 0;
        if($this->order)
            $total = $this->order->getTotal();
    ?>

    <div class="top">
        <div class="label fl_l" id="<?=$this->dateNow->getTimestamp()?>">Стоимость заказа - <?=$total?></div>
    </div>
    <?php if(count($this->menus) != 0):?>
        <ul>
            <?php
            $group = "";
            foreach($this->menus as $menu)
            {
                if (!$menu->isDeleted()){
                    $dg = $menu->getDish()->getGroup()->getName();
                    if ($group != $dg)
                    {
                        echo "<li class='" . $this->class . " p10'>$dg";
                    }

                    $count = 0;
                    $items = [];
                    if($this->order)
                        $items = $this->order->getItem();

                    foreach($items as $item)
                    {
                        if ($item->getDish()->getId() == $menu->getDish()->getId())
                            $count = $item->getCount();
                    }

                    echo "
                        <li class='li_dish'>
                            <table>
                                <tr>
                                    <td style='width:435px; padding-left:10px; font-size: 14px'>
                                        {$menu->getDish()->getName()}
                                    </td>
                                    <td width=50>
                                        {$menu->getDish()->getCost()}
                                    </td>
                                    <td width=30>
                                        <div class='count'>$count</div>
                                    </td>
                                    <td width=140>";
                    if ($this->class == "li_group"){
                        echo "
                                        <button class='button3 fl_r btt_add' id='{$menu->getDish()->getId()}'>Добавить</button>
                                        <button class='button2 fl_r btt_remove' id='{$menu->getDish()->getId()}'>Убрать</button>
                             ";
                    }
                    echo "
                                    </td>
                                </tr>
                            </table>
                        </li>";
                    if ($group != $dg)
                    {
                        $group = $dg;
                        echo "</li>";
                    }
                }
            }
            ?>
        </ul>
    <?php else:?>
        <div>На этот день меню не сформировано</div>
    <?php endif;?>
</div>