<?php $this->headScript()->appendFile('/js/order.js'); ?>
<div class="dcontent">
    <div style="margin-left: 10px;">
        <?php foreach($this->dates as $date):?>
            <a href="/menu/<?=$date['timestamp']?>" class="<?=$date['class']?>"><?=$date['date']?></a>
        <?php endforeach;?>
    </div>

    <div class="top">
        <div class="label fl_l" id="<?=$this->dateNow->getTimestamp()?>">Стоимость заказа - </div>
    </div>
    <?php if(count($this->menus) != 0):?>
        <ul>
            <?php
            $group = "";
            foreach($this->menus as $menu)
            {
                $dg = $menu->getDish()->getGroup()->getName();
                if ($group != $dg)
                {
                    echo "<li class='li_group p10'>$dg";
                }

                echo "
                    <li class='li_dish'>
                        <table>
                            <tr>
                                <td style='width:435px; padding-left:10px; font-size: 14px'>
                                    {$menu->getDish()->getName()}
                                </td>
                                <td width=50>
                                    {$menu->getDish()->getCost()}
                                </td>
                                <td width=30>
                                    <div class='count'>0</div>
                                </td>
                                <td width=140>
                                    <button class='button3 fl_r btt_add' id='{$menu->getDish()->getId()}'>Добавить</button>
                                    <button class='button2 fl_r btt_remove' id='{$menu->getDish()->getId()}'>Убрать</button>
                                </td>
                            </tr>
                        </table>
                    </li>";
                if ($group != $dg)
                {
                    $group = $dg;
                    echo "</li>";
                }
            }
            ?>
        </ul>
    <?php else:?>
        <div>На этот день меню не сформировано</div>
    <?php endif;?>
</div>