<?php $this->headScript()->appendFile('/js/order.js'); ?>
<div class="dcontent">
    <div style="margin-left: 10px;">
        <?php foreach($this->dates as $date):?>
            <a href="/order/<?=$date['timestamp']?>" class="<?=$date['class']?>"><?=$date['date']?></a>
        <?php endforeach;?>
    </div>
    <?php
        $total = 0;
        if($this->order)
            $total = $this->order->getTotal();
    ?>

    <div class="top">
        <div class="label fl_l" id="<?=$this->dateNow->getTimestamp()?>"><div class='fl_r total_cost'><?=$total?></div>Стоимость заказа -&nbsp;</div>
        <a href="#null" class="button1 fl_r show_my">Только заказанное</a>
        <a href="#null" class="button1 fl_r show_all" style="display:none;">Все меню</a>
    </div>
    <?php if(count($this->menus) != 0):?>
        <ul>
            <?php

            if ($this->class == 'li_group')
            {
                $group = "";
                foreach($this->menus as $menu)
                {
                    if (!$menu->isDeleted()){
                        $dg = $menu->getDish()->getGroup()->getName();

                        $count = 0;
                        $items = [];
                        if($this->order)
                            $items = $this->order->getItem();

                        foreach($items as $item)
                        {
                            if ($item->getDish()->getId() == $menu->getDish()->getId())
                                $count = $item->getCount();
                        }

                        if ($group != $dg)
                        {
                            echo "<li class='" . $this->class . " p10'>$dg";
                        }

                        $class_tr = $count == 0 ? 'pre_hidden' : '';

                        echo "
                        <li class='li_dish'>
                            <table>
                                <tr class='$class_tr'>
                                    <td style='width:435px; padding-left:10px; font-size: 14px'>
                                        {$menu->getDish()->getName()}
                                    </td>
                                    <td width=50>
                                        {$menu->getDish()->getCost()}
                                    </td>
                                    <td width=30>
                                        <div class='count'>$count</div>
                                    </td>
                                    <td width=140>";
                        if ($this->class == "li_group"){
                            echo "
                                        <button class='button3 fl_r btt_add' id='{$menu->getDish()->getId()}'>Добавить</button>
                                        <button class='button2 fl_r btt_remove' id='{$menu->getDish()->getId()}'>Убрать</button>
                             ";
                        }
                        echo "
                                    </td>
                                </tr>
                            </table>
                        </li>";
                        if ($group != $dg)
                        {
                            $group = $dg;
                            echo "</li>";
                        }
                    }
                }
            } else {
                echo "<li class='li_group_close p10'>Ваш заказ</li>";
                if($this->order){
                    $orderItems = $this->order->getItem();
                    foreach($orderItems as $item)
                    {
                        echo "
                            <li class='li_dish'>
                                <table><tr>
                                    <td width=480 style='padding-left:10px;'>" . $item->getDish()->getName() . "</td>
                                    <td width=40>" . $item->getCount() . "</td>
                                    <td class='button3 d_n'>Вкусно</td>
                                    <td class='button2 d_n'>Не вкусно</td>
                                </tr></table>
                            </li>";
                    }
                }
            }

            ?>
        </ul>
    <?php else:?>
        <div>На этот день меню не сформировано</div>
    <?php endif;?>
</div>